// Textos fixos do laudo-modelo da psicóloga (MentEssence), palavra por palavra. São o conteúdo padrão do modelo "Laudo neuropsicológico completo";
// quem quiser outra redação grava uma cópia do modelo com outro nome (ver modelos.ts). Não "melhorar" aqui.
export const TEXTO_REFERENCIAL = [
  "Miotto (2017) define a Neuropsicologia como uma ciência interdisciplinar que tem como objetivo o estudo da cognição e do comportamento de um indivíduo em relação ao seu Sistema Nervoso Central (SNC). Miotto, Campanholo, Trevisan e Serrão (2018) compreendem a avaliação neuropsicológica como um processo técnico e científico em que se obtêm informações a partir de instrumentos, técnicas e métodos específicos, nas quais são realizadas interpretações das informações obtidas. Assim como os dados quantitativos obtidos na testagem cognitiva, é importante realizar uma análise quantitativa que envolve observação clínica das verbalizações, gestos, humor, tom de voz, hábitos e demais idiossincrasias que podem oferecer informações acerca do ajustamento comportamental, dinâmica familiar e estilo de vida do paciente (Campanholo & Serrão, 2018). Lezak, Howieson & Loring (2004) propõem seis objetivos principais para a avaliação neuropsicológica: pesquisa, resposta a solicitação forense, diagnóstico, cuidado com paciente, identificação das necessidades e eficácia do tratamento.",
  "A análise de tarefas qualitativas, fundamentada em estudos preliminares, foi integrada aos textos interpretativos deste relatório, com as referências sendo inseridas no final do relatório. A classificação foi conduzida segundo os critérios delineados na tabela a seguir.",
];
export const AVISO_SIGILO = "Este laudo não poderá ser utilizado para fins diferentes do apontado no item de identificação, o mesmo possui caráter sigiloso e se trata de documento extrajudicial e a autora não se responsabiliza pelo uso dado ao laudo por parte solicitante, após a sua entrega em entrevista devolutiva, conforme normas éticas propostas pelo Conselho Federal de Psicologia.";
export const AVISO_VALIDADE = "VALIDADE: Conforme normas do Conselho Federal de Psicologia, o documento possui validade de 05 anos. Porém, o desenvolvimento das funções cognitivas é dinâmico e fluido, suscetível a modificações no decorrer do tempo. Desta forma, as informações e resultados deste relatório referem-se ao padrão de funcionamento cognitivo atual, mantendo fidedignidade (confiabilidade) por aproximadamente 1 ano. Ou seja, após aproximadamente 1 ano da presente avaliação, os resultados aqui descritos podem não representar adequadamente o padrão de funcionamento cognitivo do(a) paciente.";
export const AVISO_IA = "Este laudo contou com apoio de Inteligência Artificial na redação de rascunho de partes do texto, integralmente revisado e assumido pelo(a) profissional responsável, conforme a Resolução CFP nº 09/2024 e a cartilha do CFP sobre o uso de IA.";
